# Generated by Django 2.2.11 on 2020-03-21 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edges', '0002_edge_edgeid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edge',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='edge',
            name='edgeid',
        ),
        migrations.RemoveField(
            model_name='edge',
            name='gray_scale',
        ),
        migrations.RemoveField(
            model_name='edge',
            name='image',
        ),
        migrations.AddField(
            model_name='edge',
            name='gray_scale_setting',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='edge',
            name='time_setting',
            field=models.FloatField(default=60),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/')),
                ('gray_scale', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edge_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edges.Edge')),
            ],
        ),
    ]
