# Generated by Django 2.2.11 on 2020-03-22 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edges', '0003_auto_20200321_1339'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
