# Generated by Django 2.2.11 on 2020-03-23 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edges', '0004_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.TextField(),
        ),
    ]
